In [73]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import math

In [74]:
def distanciaEuclideana(obj1, obj2):
    sum = 0
    for i in range(0,len(obj1)):
        sum += (obj1[i] - obj2[i])**2
    res = math.sqrt(sum)
    return res

def create_euclidean_distance_list(characteristics: list, center: list) -> list:
    distancias = []
    for element in characteristics:
        distancias.append(distanciaEuclideana(center, element))
    return distancias

In [75]:
data = np.array([[1, 14.23, 5.64, 1065],
        [1, 13.2, 4.38, 1050],
        [1, 13.16, 5.68, 1185],
        [2, 12.33, 3.27, 680],
        [2, 12.64, 5.75, 450],
        [2, 13.67, 3.8, 630],
        [3, 12.93, 4.6, 600],
        [3, 13.36, 5.6, 780],
        [3, 13.52, 4.35, 520]])

In [91]:
k = 3

characteristics = data[:,1:4]
print(characteristics)

scaler = StandardScaler()

scaler.fit(characteristics)

characteristics = scaler.transform(characteristics)

print(characteristics)

[[  14.23    5.64 1065.  ]
 [  13.2     4.38 1050.  ]
 [  13.16    5.68 1185.  ]
 [  12.33    3.27  680.  ]
 [  12.64    5.75  450.  ]
 [  13.67    3.8   630.  ]
 [  12.93    4.6   600.  ]
 [  13.36    5.6   780.  ]
 [  13.52    4.35  520.  ]]
[[ 1.88552675  0.98441158  1.17015634]
 [-0.05011367 -0.46724347  1.10997687]
 [-0.12528417  1.03049587  1.65159209]
 [-1.68507208 -1.74608245 -0.37445003]
 [-1.10250069  1.11114337 -1.29720188]
 [ 0.83313973 -1.13546564 -0.57504826]
 [-0.55751455 -0.21377989 -0.69540719]
 [ 0.25056834  0.9383273   0.02674643]
 [ 0.55125034 -0.50180669 -1.01636436]]


In [92]:
object_to_classificate = np.array([[11.65, 2.6, 562]])
object_to_classificate = scaler.transform(object_to_classificate)
print(object_to_classificate)

[[-2.9629706  -2.51799426 -0.84786185]]


In [93]:
distances = create_euclidean_distance_list(characteristics=characteristics, center=object_to_classificate[0])
print(distances)
distances = np.array(distances)

distances_sort = np.sort(distances)
print(distances_sort)

[6.3124615354669285, 4.064904274449919, 5.185703084185502, 1.5662028106594026, 4.102912958125259, 4.049230330261266, 3.334496228430921, 4.799784461279446, 4.055015943019649]
[1.56620281 3.33449623 4.04923033 4.05501594 4.06490427 4.10291296
 4.79978446 5.18570308 6.31246154]


In [94]:
ranked_distances = distances_sort[0:k]
print(ranked_distances)

[1.56620281 3.33449623 4.04923033]


In [95]:
for i in np.arange(k):
    print(np.where(distances == ranked_distances[i])[0][0])

3
6
5
