In [9]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.metrics import classification_report


import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.preprocessing import OneHotEncoder

from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold

import seaborn as sns
import warnings

In [10]:
pred = ["BS","DC","DC","BS","CR","CR","CR","CR","BS","BS","CR","DC","BS","BS","CR"]
real = ["DC","DC","DC","DC","DC","CR","CR","CR","CR","CR","BS","BS","BS","BS","BS"]

In [11]:
cm = confusion_matrix(y_true=real, y_pred=pred)
print(cm)

[[2 2 1]
 [2 3 0]
 [2 1 2]]


In [13]:
print(classification_report(y_pred=pred, y_true=real))

              precision    recall  f1-score   support

          BS       0.33      0.40      0.36         5
          CR       0.50      0.60      0.55         5
          DC       0.0.40      0.50         5

    accuracy                           0.47        15
   macro avg       0.50      0.47      0.47        15
weighted avg       0.50      0.47      0.47        15

