In [317]:
import numpy as np
from sklearn.preprocessing import normalize
import math

In [318]:
data = np.array([[99.8, 176.6, 66.2, 54.3, 0.2, 0.98],
        [99.4, 176.6, 66.4, 54.3, 0.5, 0.7],
        [99.8, 177.3, 66.3, 53.1, 0.25, 0.35],
        [105.8, 192.7, 71.4, 55.7, 0.45, 0.65],
        [95.3, 169, 65.7, 49.6, 0.15, 0.95],
        [98.8, 177.8, 66.5, 53.7, 0.66, 0.23],
        [98.8, 177.8, 66.5, 55.5, 0.1, 0.87],
        [107.9, 186.7, 68.4, 56.7, 0.95, 0.35],
        [107.9, 186.7, 68.4, 56.7, 0.15, 0.25],
        [104.3, 188.8, 67.2, 57.5, 0.35, 0.35]])

In [319]:
C = 2
b = 1.5
e = 0.1

In [320]:
def distanciaEuclideana(obj1, obj2):
    sum = 0
    for i in range(0,len(obj1)):
        sum += (obj1[i] - obj2[i])**2
    res = math.sqrt(sum)
    return res

In [321]:
beta_array = []

pertenetial_values1 = data[:,4:5]
pertenetial_values2 = data[:,5:6]

for i in np.arange(pertenetial_values1.shape[0]):
    beta_array.append((1/(pertenetial_values1[i] + pertenetial_values2[i]))[0])

#Normalize characteristics 
for i in np.arange(pertenetial_values1.shape[0]):
    pertenetial_values1[i] = pertenetial_values1[i] * beta_array[i]
    pertenetial_values2[i] = pertenetial_values2[i] * beta_array[i]


In [322]:
characteristics = data[:,0:4]

i = 0
sumatoria1 = np.zeros((1, characteristics.shape[1]))
for element in pertenetial_values1:
    sumatoria1 += pow(element, b) * characteristics[i]
    i += 1

sumatoria2 = np.zeros((1, characteristics.shape[1]))
for element in pertenetial_values1:
    sumatoria2 += pow(element, b) 

mui1 = sumatoria1/sumatoria2
mui1 = mui1[0]
print(mui1)


#---------------------

i = 0
sumatoria1 = np.zeros((1, characteristics.shape[1]))
for element in pertenetial_values2:
    sumatoria1 += pow(element, b) * characteristics[i]
    i += 1

sumatoria2 = np.zeros((1, characteristics.shape[1]))
for element in pertenetial_values2:
    sumatoria2 += pow(element, b) 

mui2 = sumatoria1/sumatoria2
mui2 = mui2[0]
print(mui2)

[103.04194471 182.9467417   67.57560343  55.24496478]
[100.7603177  179.35340413  67.04888807  54.28400845]


In [323]:
#Actualizar la pertenencia de cada objeto de los grupos
#Obtener la distancia Euclideana del centro al objeto
distancias1 = []
distancias2 = []
for element in characteristics:
    distancias1.append(distanciaEuclideana(mui1, element))
    distancias2.append(distanciaEuclideana(mui2, element))

print(distancias1)
print(distancias2)

[7.319602371225332, 7.471271194766701, 6.97308649701471, 10.84278482303101, 17.02447730189181, 6.930143137096687, 6.7605481048877065, 6.362735756986924, 6.362735756986924, 6.4085565979158226]
[3.037155100004105, 3.1389504667803148, 2.664842957303909, 14.9822303396374, 12.679411689057515, 2.626452718171134, 2.834752802043298, 10.61178838588729, 10.61178838588729, 10.589285182427885]


In [324]:
#Nuevas pertenencias
sumatoria_distancias1 = 0
for element in distancias1:
    sumatoria_distancias1 += pow((1 / pow(element, 2)), (1/(b-1)))

sumatoria_distancias2 = 0
for element in distancias2:
    sumatoria_distancias2 += pow((1 / pow(element, 2)), (1/(b-1)))

for i in np.arange(pertenetial_values1.shape[0]):
    pertenetial_values1[i] = pow((1 / pow(distancias1[i], 2)), (1/(b-1))) / sumatoria_distancias1
    pertenetial_values2[i] = pow((1 / pow(distancias2[i], 2)), (1/(b-1))) / sumatoria_distancias2

In [325]:
print(pertenetial_values1)
print(pertenetial_values2)

[[0.08928365]
 [0.08225151]
 [0.1083981 ]
 [0.01854208]
 [0.00305089]
 [0.11110998]
 [0.12268579]
 [0.15636744]
 [0.15636744]
 [0.1519431 ]]
[[1.49373160e-01]
 [1.30918977e-01]
 [2.52031005e-01]
 [2.52251974e-04]
 [4.91749628e-04]
 [2.67092753e-01]
 [1.96824737e-01]
 [1.00227323e-03]
 [1.00227323e-03]
 [1.01082011e-03]]
