In [1]:
import numpy as np
from sklearn.preprocessing import normalize
import math
import random

In [2]:
def distanciaEuclideana(obj1, obj2):
    sum = 0
    for i in range(0,len(obj1)):
        sum += (obj1[i] - obj2[i])**2
    res = math.sqrt(sum)
    return res

def create_euclidean_distance_list(characteristics: list, center: list) -> list:
    distancias = []
    for element in characteristics:
        distancias.append(distanciaEuclideana(center, element))
    return distancias

def update_group_means(characteristics: list, pertenetial_values:list, b: int or float) ->list:
    i = 0
    sumatoria1 = np.zeros((1, characteristics.shape[1]))
    for element in pertenetial_values:
        sumatoria1 += pow(element, b) * characteristics[i]
        i += 1

    sumatoria2 = np.zeros((1, characteristics.shape[1]))
    for element in pertenetial_values:
        sumatoria2 += pow(element, b)

    mui = sumatoria1/sumatoria2
    mui = mui[0]
    return mui

In [8]:
data = np.array([[99.8, 176.6, 66.2, 54.3, 0.2, 0.98],
        [99.4, 176.6, 66.4, 54.3, 0.5, 0.7],
        [99.8, 177.3, 66.3, 53.1, 0.25, 0.35],
        [105.8, 192.7, 71.4, 55.7, 0.45, 0.65],
        [95.3, 169, 65.7, 49.6, 0.15, 0.95],
        [98.8, 177.8, 66.5, 53.7, 0.66, 0.23],
        [98.8, 177.8, 66.5, 55.5, 0.1, 0.87],
        [107.9, 186.7, 68.4, 56.7, 0.95, 0.35],
        [107.9, 186.7, 68.4, 56.7, 0.15, 0.25],
        [104.3, 188.8, 67.2, 57.5, 0.35, 0.35]])

In [9]:
ListOfListType = list[list]

def create_pertenetial_values(length: int, size: int) -> ListOfListType:
    pertenetials_values = []
    for i in np.arange(length):
        values = []
        for j in np.arange(size):
            values.append(random.uniform(0,1))
        pertenetials_values.append(values)
    pertenetials_values = np.array(pertenetials_values)

    beta_array = []
    for i in np.arange(pertenetials_values.shape[1]):
        sumatory = 0
        for j in np.arange(pertenetials_values.shape[0]):
            sumatory += pertenetials_values[j][i]
        beta_array.append(1 / sumatory)
    
    #Normalize
    for i in np.arange(pertenetials_values.shape[1]):
        for j in np.arange(pertenetials_values.shape[0]):
            pertenetials_values[j][i] = pertenetials_values[j][i] * beta_array[i]
    return pertenetials_values

In [10]:
C = 2
b = 1.5
e = 0.1
pertenetial_values1 = data[:,4:5]
pertenetial_values2 = data[:,5:6]


beta_array = []

for i in np.arange(pertenetial_values1.shape[0]):
    beta_array.append((1/(pertenetial_values1[i] + pertenetial_values2[i]))[0])

#Normalize characteristics 
for i in np.arange(pertenetial_values1.shape[0]):
    pertenetial_values1[i] = pertenetial_values1[i] * beta_array[i]
    pertenetial_values2[i] = pertenetial_values2[i] * beta_array[i]

#Select characteristics
characteristics = data[:,0:4]

In [11]:
last_mean2 = []

for i in np.arange(10):
    mui1 = update_group_means(characteristics=characteristics, pertenetial_values=pertenetial_values1, b=b)
    mui2 = update_group_means(characteristics=characteristics, pertenetial_values=pertenetial_values2, b=b)

    last_mean1 = mui1
    last_mean2 = mui2

    print(last_mean1, last_mean2)

    distancias1 = create_euclidean_distance_list(characteristics=characteristics, center=mui1)
    distancias2 = create_euclidean_distance_list(characteristics=characteristics, center=mui2)

    #Nuevas pertenencias
    sumatoria_distancias11 = []
    for element in distancias1:
        sumatoria_distancias11.append(pow((1 / pow(element, 2)), (1/(b-1))))

    sumatoria_distancias22 = []
    for element in distancias2:
        sumatoria_distancias22.append(pow((1 / pow(element, 2)), (1/(b-1))))

    for i in np.arange(pertenetial_values1.shape[0]):
        pertenetial_values1[i] = pow((1 / pow(distancias1[i], 2)), (1/(b-1))) / (sumatoria_distancias11[i] + sumatoria_distancias22[i])
        pertenetial_values2[i] = pow((1 / pow(distancias2[i], 2)), (1/(b-1))) / (sumatoria_distancias11[i] + sumatoria_distancias22[i])
    
    group1 = []
    group2 = []

    for i in np.arange(pertenetial_values1.shape[0]):
        if(pertenetial_values1[i] > pertenetial_values2[i]):
            group1.append(i)
        else:
            group2.append(i)
    
    print(group1)
    print(group2)
    print("-----------------------------------------------------------------------------------------------------------------")
    

[103.04194471 182.9467417   67.57560343  55.24496478] [100.7603177  179.35340413  67.04888807  54.28400845]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.07735028 187.80882666  68.62281374  56.43138429] [ 99.1137311  176.7392231   66.42159151  53.72292761]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.46358582 188.68616168  68.83792694  56.64381924] [ 98.67608953 175.90335355  66.27165955  53.44506267]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.47023605 188.70896738  68.84527878  56.64726239] [ 98.66410998 175.87813576  66.26915075  53.43163116]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
--------------------------------------------------------------------------------------------------