In [167]:
import numpy as np
from sklearn.preprocessing import normalize
import math
import random

In [168]:
def distanciaEuclideana(obj1, obj2):
    sum = 0
    for i in range(0,len(obj1)):
        sum += (obj1[i] - obj2[i])**2
    res = math.sqrt(sum)
    return res

def update_group_means(characteristics: list, pertenetial_values:list, b: int or float) ->list:
    i = 0
    sumatoria1 = np.zeros((1, characteristics.shape[1]))
    for element in pertenetial_values:
        sumatoria1 += pow(element, b) * characteristics[i]
        i += 1

    sumatoria2 = np.zeros((1, characteristics.shape[1]))
    for element in pertenetial_values:
        sumatoria2 += pow(element, b)

    mui = sumatoria1/sumatoria2
    mui = mui[0]
    return mui

def create_euclidean_distance_list(characteristics: list, center: list) -> list:
    distancias = []
    for element in characteristics:
        distancias.append(distanciaEuclideana(center, element))
    return distancias

In [169]:
import numpy as np
#import cv2

path = "/Users/samuelguerrero/Downloads/pelotas.jpg"
#img = cv2.imread(path, 1)
#print(img)

In [170]:
data = np.array([[99.8, 176.6, 66.2, 54.3, 0.2, 0.98],
        [99.4, 176.6, 66.4, 54.3, 0.5, 0.7],
        [99.8, 177.3, 66.3, 53.1, 0.25, 0.35],
        [105.8, 192.7, 71.4, 55.7, 0.45, 0.65],
        [95.3, 169, 65.7, 49.6, 0.15, 0.95],
        [98.8, 177.8, 66.5, 53.7, 0.66, 0.23],
        [98.8, 177.8, 66.5, 55.5, 0.1, 0.87],
        [107.9, 186.7, 68.4, 56.7, 0.95, 0.35],
        [107.9, 186.7, 68.4, 56.7, 0.15, 0.25],
        [104.3, 188.8, 67.2, 57.5, 0.35, 0.35]])

In [171]:
ListOfListType = list[list]

def create_pertenetial_values(length: int, size: int) -> ListOfListType:
    pertenetials_values = []
    for i in np.arange(length):
        values = []
        for j in np.arange(size):
            values.append(random.uniform(0,1))
        pertenetials_values.append(values)
    pertenetials_values = np.array(pertenetials_values)

    beta_array = []
    for i in np.arange(pertenetials_values.shape[1]):
        sumatory = 0
        for j in np.arange(pertenetials_values.shape[0]):
            sumatory += pertenetials_values[j][i]
        beta_array.append(1 / sumatory)
    
    #Normalize
    for i in np.arange(pertenetials_values.shape[1]):
        for j in np.arange(pertenetials_values.shape[0]):
            pertenetials_values[j][i] = pertenetials_values[j][i] * beta_array[i]
    return pertenetials_values

In [174]:
C = 2
b = 1.5
e = 0.1

pertenetial_values = create_pertenetial_values(length=3, size=10)

#Array
characteristics = data[:,0:4]

last_mean = []
muis = []

for element in pertenetial_values:
    muis.append([])
    last_mean.append([])

#for i in np.arange(10):

for i in np.arange(pertenetial_values.shape[0]):
    muis[i] = update_group_means(characteristics=characteristics, pertenetial_values=pertenetial_values[i], b=b).tolist()
    last_mean[i] = muis[i]

distances = []

for element in muis:
    distances.append(create_euclidean_distance_list(characteristics=characteristics, center=element))
print(distances)


[[6.258175565478759, 6.435665808985866, 5.978615066368678, 11.978811309443604, 16.034960939047753, 6.003077670873893, 5.811306821468215, 7.220446801931061, 7.220446801931061, 7.423478865158474], [4.1677064846414895, 4.284002708870545, 3.6907375453108333, 13.8719675921914, 13.719644102540068, 3.6792584653054434, 3.8700522835222855, 9.566708056111526, 9.566708056111526, 9.561343598574659], [4.847928341957529, 4.955646661298621, 4.518656367216522, 13.1662877653451, 14.537262331162003, 4.388609778606273, 4.2885316652548156, 8.870291059862915, 8.870291059862915, 8.764301885903306]]


In [173]:
for i in np.arange(10):
    mui1 = update_group_means(characteristics=characteristics, pertenetial_values=pertenetial_values1, b=b)
    mui2 = update_group_means(characteristics=characteristics, pertenetial_values=pertenetial_values2, b=b)

    last_mean1 = mui1
    last_mean2 = mui2

    print(last_mean1, last_mean2)

    distancias1 = create_euclidean_distance_list(characteristics=characteristics, center=mui1)
    distancias2 = create_euclidean_distance_list(characteristics=characteristics, center=mui2)

    #Nuevas pertenencias
    sumatoria_distancias11 = []
    for element in distancias1:
        sumatoria_distancias11.append(pow((1 / pow(element, 2)), (1/(b-1))))

    sumatoria_distancias22 = []
    for element in distancias2:
        sumatoria_distancias22.append(pow((1 / pow(element, 2)), (1/(b-1))))

    for i in np.arange(pertenetial_values1.shape[0]):
        pertenetial_values1[i] = pow((1 / pow(distancias1[i], 2)), (1/(b-1))) / (sumatoria_distancias11[i] + sumatoria_distancias22[i])
        pertenetial_values2[i] = pow((1 / pow(distancias2[i], 2)), (1/(b-1))) / (sumatoria_distancias11[i] + sumatoria_distancias22[i])
    
    group1 = []
    group2 = []

    for i in np.arange(pertenetial_values1.shape[0]):
        if(pertenetial_values1[i] > pertenetial_values2[i]):
            group1.append(i)
        else:
            group2.append(i)
    
    print(group1)
    print(group2)
    print("-----------------------------------------------------------------------------------------------------------------")
    
#print(last_mean1, last_mean2)

[106.47035154 188.70941418  68.84542493  56.64732628] [ 98.6638344  175.87754173  66.26909471  53.43130219]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.47035154 188.70941418  68.84542493  56.64732628] [ 98.6638344  175.87754173  66.26909471  53.43130219]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.47035154 188.70941418  68.84542493  56.64732628] [ 98.6638344  175.87754173  66.26909471  53.43130219]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
-----------------------------------------------------------------------------------------------------------------
[106.47035154 188.70941418  68.84542493  56.64732628] [ 98.6638344  175.87754173  66.26909471  53.43130219]
[3, 7, 8, 9]
[0, 1, 2, 4, 5, 6]
--------------------------------------------------------------------------------------------------